############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://127.0.0.1:3306/foodieShop?characterEncoding=utf8&useSSL=false
    password: 12345678
  redis:
    database: 1
    port: 6379
    host: localhost
    password: arlenChen

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl